export const groups = [
  {
    id: 100001,
    groupName: "Beach Bums",
    members: [
      {
        id: 100001,
        name: "John Doe",
        phone: "+1234567890",
        imageUrl: "/profile_imgs/image-1.jpeg",
      },
    ],
  },
  {
    id: 100002,
    groupName: "Mountain Mavericks cosatee",
    members: [
      {
        id: 100002,
        name: "Jane Smith",
        phone: "+1987654321",
        imageUrl: "/profile_imgs/image-2.jpeg",
      },
    ],
  },
  {
    id: 100003,
    groupName: "City Slickers",
    members: [
      {
        id: 100003,
        name: "Michael Johnson",
        phone: "+1122334455",
        imageUrl: "/profile_imgs/image-3.jpeg",
      },
    ],
  },
  {
    id: 100004,
    groupName: "Nature Lovers",
    members: [
      {
        id: 100004,
        name: "Emily Davis",
        phone: "+1555666777",
        imageUrl: "/profile_imgs/image-4.jpeg",
      },
    ],
  },
  {
    id: 100005,
    groupName: "Foodie Fiesta",
    members: [
      {
        id: 100005,
        name: "David Wilson",
        phone: "+1444333222",
        imageUrl: "/profile_imgs/image-5.jpeg",
      },
    ],
  },
  {
    id: 100006,
    groupName: "Adventure Explorers",
    members: [
      {
        id: 100006,
        name: "Sarah Brown",
        phone: "+1888777666",
        imageUrl: "/profile_imgs/image-6.jpeg",
      },
    ],
  },
  {
    id: 100007,
    groupName: "Road Trip Crew",
    members: [
      {
        id: 100007,
        name: "Daniel Kim",
        phone: "+1223344556",
        imageUrl: "/profile_imgs/image-7.jpeg",
      },
    ],
  },
  {
    id: 100008,
    groupName: "Nightlife Squad",
    members: [
      {
        id: 100008,
        name: "Olivia Garcia",
        phone: "+1666777888",
        imageUrl: "/profile_imgs/image-8.jpeg",
      },
    ],
  },
  {
    id: 100009,
    groupName: "Culture Club",
    members: [
      {
        id: 100009,
        name: "James Wilson",
        phone: "+1999888777",
        imageUrl: "/profile_imgs/image-9.jpeg",
      },
    ],
  },
  {
    id: 100010,
    groupName: "Art Aficionados",
    members: [
      {
        id: 100001,
        name: "Sophia Lee",
        phone: "+1333222111",
        imageUrl: "/profile_imgs/image-10.jpeg",
      },
      {
        id: 100002,
        name: "La Lee",
        phone: "+1444222111",
        imageUrl: "/profile_imgs/image-11.jpeg",
      },
    ],
  },
];
export const groupData = [
  {
    "S.No": 1,
    Name: "John Marshallmellow Deacosta",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 2,
    Name: "Emily",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 3,
    Name: "Michael",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 4,
    Name: "Sarah",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 5,
    Name: "David",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 6,
    Name: "Olivia",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 7,
    Name: "Daniel",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 8,
    Name: "Emma",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 9,
    Name: "Ethan",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 10,
    Name: "Ava",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 11,
    Name: "Mia",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 12,
    Name: "Jackson",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 13,
    Name: "Sophia",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 14,
    Name: "William",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 15,
    Name: "Oliver",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 16,
    Name: "Chloe",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 17,
    Name: "Daniel",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 18,
    Name: "Sophie",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 19,
    Name: "Lucas",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 20,
    Name: "Amelia",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 21,
    Name: "Liam",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 22,
    Name: "Emma",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 23,
    Name: "Noah",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 24,
    Name: "Olivia",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 25,
    Name: "William",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 26,
    Name: "James",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 27,
    Name: "Ava",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 28,
    Name: "Alexander",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 29,
    Name: "Mia",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 30,
    Name: "Ethan",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 31,
    Name: "Isabella",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 32,
    Name: "Sophia",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 33,
    Name: "Jackson",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 34,
    Name: "Charlotte",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
  {
    "S.No": 35,
    Name: "Lucas",
    Contribution: 150,
    Dues: 0,
    Settled: "settled",
  },
  {
    "S.No": 36,
    Name: "Avery",
    Contribution: 200,
    Dues: 25,
    Settled: "pending",
  },
  {
    "S.No": 37,
    Name: "Amelia",
    Contribution: 125,
    Dues: 75,
    Settled: "pending",
  },
  {
    "S.No": 38,
    Name: "Benjamin",
    Contribution: 50,
    Dues: 150,
    Settled: "pending",
  },
  {
    "S.No": 39,
    Name: "Harper",
    Contribution: 100,
    Dues: 50,
    Settled: "pending",
  },
  {
    "S.No": 40,
    Name: "Evelyn",
    Contribution: 75,
    Dues: 100,
    Settled: "pending",
  },
];
